//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaOnDemandLibrary {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class ProjectSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ProjectSettings defaultInstance = ((ProjectSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ProjectSettings())));
        
        public static ProjectSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
