<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true"
    CodeBehind="SiteAdministration.aspx.cs" Inherits="MediaOnDemand.SiteAdministration" %>

<%@ Register Assembly="System.Web.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
    Namespace="System.Web.UI.WebControls" TagPrefix="asp" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <h1>
        Site Administration</h1>
    <table>
        <tr>
            <td colspan="2">
                <asp:Label ID="lblEnterSqlQuery" runat="server" Text="Enter SQL Query to Execute: "></asp:Label>
            </td>
        </tr>
        <tr>
            <td style="width: 60%">
                <asp:TextBox ID="txtSQLQuery" Width="95%" TextMode="MultiLine" runat="server" AutoPostBack="True"></asp:TextBox>
            </td>
            <td align="left">
                <%--<asp:RequiredFieldValidator ID="reqSqlQuery" runat="server" ErrorMessage="field is requred"
                    ControlToValidate="txtSQLQuery"></asp:RequiredFieldValidator>--%>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <table>
                    <tr>
                        <td>
                            <asp:Button ID="btnExecuteQuery" OnClientClick="" runat="server" Text="Execute Query"
                                OnClick="btnExecuteQuery_Click" />
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                <asp:Label ID="lblErrors" runat="server" ForeColor="Red" Text=""></asp:Label>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <asp:Panel ID="QueryResultsPanel" ScrollBars="Horizontal" Width="1175px" runat="server">
                    <asp:GridView ID="gvQueryResults" Width="600px" runat="server" AutoGenerateColumns="true"
                        DataSourceID="SqlDataSource" EnableModelValidation="True" ScrollBars="" AllowPaging="True"
                        AllowSorting="True" CellPadding="4" DataKeyNames="medId" ForeColor="#333333"
                        GridLines="None" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                        <Columns>
                        </Columns>
                        <EditRowStyle BackColor="#999999" />
                        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                        <EmptyDataTemplate>
                            <table cellspacing="0" cellpadding="4" border="0" id="ctl00_MainContent_gvMedia"
                                style="color: #333333; border-collapse: collapse;" width="100%">
                                <tr align="left" style="color: White; background-color: #284775;">
                                    <td colspan="12">
                                    </td>
                                </tr>
                                <tr style="color: White; background-color: #5D7B9D; font-weight: bold;">
                                    <th scope="col">
                                        <a style="color: White;"><u>Title</u></a>
                                    </th>
                                    <th scope="col">
                                        <a style="color: White;"><u>Location</u></a>
                                    </th>
                                    <th scope="col">
                                        <a style="color: White;"><u>Description</u></a>
                                    </th>
                                    <th scope="col">
                                        <a style="color: White;"><u>Is Viewable</u></a>
                                    </th>
                                    <th scope="col">
                                        <a style="color: White;"><u>Artist</u></a>
                                    </th>
                                    <th scope="col">
                                        <a style="color: White;"><u>Genre</u></a>
                                    </th>
                                    <th scope="col">
                                        <a style="color: White;"><u>Media Type</u></a>
                                    </th>
                                    <th scope="col">
                                        <a style="color: White;"><u>Duration</u></a>
                                    </th>
                                    <th scope="col">
                                        <a style="color: White;"><u>Album</u></a>
                                    </th>
                                    <th scope="col">
                                        <a style="color: White;"><u>File Type</u></a>
                                    </th>
                                </tr>
                                <tr>
                                    <td colspan="10">
                                        <center>
                                            No records found
                                        </center>
                                    </td>
                                </tr>
                            </table>
                        </EmptyDataTemplate>
                    </asp:GridView>
                </asp:Panel>
            </td>
        </tr>
    </table>
    <asp:SqlDataSource ID="SqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:aspnetdbConnectionString %>"
        SelectCommand="SELECT * FROM [StoredMedia]"></asp:SqlDataSource>
</asp:Content>
