<?xml version="1.0" encoding="utf-8"?>
<Database Name="aspnetdb" Class="StorageMediaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\aspnetdb.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="aspnetdbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.StoredMedia" Member="StoredMedias">
    <Type Name="StoredMedia">
      <Column Name="medTitle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="medLocation" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="medDateAdded" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="medIsViewable" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="medArtist" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="medDescription" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="medId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="medGenre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="medMediaType" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="medDuration" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="medAlbum" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>