delete [MEDIAONDEMANDDB].[dbo].[StoredMedia]

INSERT INTO [MEDIAONDEMANDDB].[dbo].[StoredMedia]
           ([medTitle]
           ,[medLocation]
           ,[medDateAdded]
           ,[medIsViewable]
           ,[medArtist]
           ,[medDescription]
           ,[medGenre]
           ,[medMediaType]
           ,[medDuration]
           ,[medAlbum]
           ,[medVideoType]
           ,[medFileExt]
           ,[medPosterImageUrl]
           ,[medLastPlayedDate]
           ,[medRating])  
select  [medTitle]
           ,[medLocation]
           ,[medDateAdded]
           ,[medIsViewable]
           ,[medArtist]
           ,[medDescription]
           ,[medGenre]
           ,[medMediaType]
           ,[medDuration]
           ,[medAlbum]
           ,[medVideoType]
           ,[medFileExt]
           ,[medPosterImageUrl]
           ,[medLastPlayedDate]
           ,[medRating] from  storedmedia