<?xml version="1.0" encoding="utf-8"?><Database Name="MEDIAONDEMANDDB" Class="StorageMediaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=MEDIAONDEMANDDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MEDIAONDEMANDDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserAccountSettings" Member="UserAccountSettings">
    <Type Name="UserAccountSetting">
      <Column Name="acctUserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="acctMustChangePassword" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.StoredMedia" Member="StoredMedias">
    <Type Name="StoredMedia">
      <Column Name="medTitle" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="medLocation" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="medDateAdded" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="medIsViewable" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="medArtist" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="medDescription" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="medId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="medGenre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="medMediaType" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="medDuration" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="medAlbum" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="medVideoType" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="medFileExt" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="medPosterImageUrl" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="medLastPlayedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="medrating" Member="medRating" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MediaRatings" Member="MediaRatings">
    <Type Name="MediaRating">
      <Column Name="rtgMediaId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="rtgUserName" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="rtgRating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserMediaPlayList" Member="UserMediaPlayLists">
    <Type Name="UserMediaPlayList">
      <Column Name="plstMediaId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="plstUserName" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="plstPlaylistIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="plstMediaTitle" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="plstMediaLocation" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>